baseUrl: /
languageCode: en-us
theme: stack
paginate: 5
title: Kunniii's Daily Report

languages:
    en:
        languageName: English
        title: Personal Daily Report
        weight: 1

# GA Tracking ID
googleAnalytics:

# Theme i18n support
# Available values: ar, bn, ca, de, el, en, es, fr, hu, id, it, ja, ko, nl, pt-br, th, uk, zh-cn, zh-hk, zh-tw
DefaultContentLanguage: en

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage: false

permalinks:
    posts: posts/:slug/
    pages: /:slug/

params:
    mainSections:
        - posts
    featuredImageField: image
    rssFullContent: true
    favicon:

    footer:
        since: 2021
        customText: Kunniii.github.io/personal-daily-report

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 MST

    sidebar:
        emoji: 🎯
        subtitle: Feeling motivated!! 🔥🔥🔥
        avatar:
            enabled: true
            local: true
            src: /img/user.jpeg

    article:
        math: false
        toc: true
        readingTime: true
        license:
            enabled: true
            default: Licensed under CC BY-NC-SA 4.0

    # comments:
    #     enabled: true
    #     provider: disqus

    #     disqusjs:
    #         shortname:
    #         apiUrl:
    #         apiKey:
    #         admin:
    #         adminLabel:

    #     utterances:
    #         repo:
    #         issueTerm: pathname
    #         label:

    #     remark42:
    #         host:
    #         site:
    #         locale:

    #     vssue:
    #         platform:
    #         owner:
    #         repo:
    #         clientId:
    #         clientSecret:
    #         autoCreateIssue: false

    #     # Waline client configuration see: https://waline.js.org/en/reference/component.html
    #     waline:
    #         serverURL:
    #         lang:
    #         pageview:
    #         emoji:
    #             - https://unpkg.com/@waline/emojis@1.0.1/weibo
    #         requiredMeta:
    #             - name
    #             - email
    #             - url
    #         locale:
    #             admin: Admin
    #             placeholder:

    #     twikoo:
    #         envId:
    #         region:
    #         path:
    #         lang:

    #     # See https://cactus.chat/docs/reference/web-client/#configuration for description of the various options
    #     cactus:
    #         defaultHomeserverUrl: "https://matrix.cactus.chat:8448"
    #         serverName: "cactus.chat"
    #         siteName: "" # You must insert a unique identifier here matching the one you registered (See https://cactus.chat/docs/getting-started/quick-start/#register-your-site)

    #     giscus:
    #         repo:
    #         repoID:
    #         category:
    #         categoryID:
    #         mapping:
    #         lightTheme:
    #         darkTheme:
    #         reactionsEnabled: 1
    #         emitMetadata: 0

    #     gitalk:
    #         owner:
    #         admin:
    #         repo:
    #         clientID:
    #         clientSecret:

    #     cusdis:
    #         host:
    #         id:
    widgets:
        homepage:
            - type: search
            - type: archives
              params:
                  limit: 5
            - type: categories
              params:
                  limit: 10
            - type: tag-cloud
              params:
                  limit: 10
        page:
            - type: toc

    defaultImage:
        opengraph:
            enabled: true
            local: true
            src: /img/default_1.jpeg

    colorScheme:
        # Display toggle
        toggle: true

        # Available values: auto, light, dark
        default: auto

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

### Custom menu
### See https://docs.stack.jimmycai.com/configuration/custom-menu.html
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
menu:
    main:
        - name: Home
          weight: -10
          url: /
          params:
              icon: home

        - name: About
          url: /about/
          weight: -9
          params:
              icon: user

        - name: Search
          weight: -8
          params:
              icon: search

    social:
        - identifier: github
          name: GitHub
          url: https://github.com/Kunniii
          params:
              icon: brand-github

        - identifier: link
          name: Other Site
          url: https://codechovui.github.io
          params:
              icon: earth

        - identifier: facebook
          name: Other Site
          url: https://fb.com/Nguyen.PhiTruong.5801
          params:
              icon: brand-facebook

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    goldmark:
        renderer:
            ## Set to true if you have HTML content inside Markdown
            unsafe: false
    tableOfContents:
        endLevel: 4
        ordered: true
        startLevel: 2
    highlight:
        noClasses: false
        codeFences: true
        guessSyntax: true
        lineNoStart: 1
        lineNos: true
        lineNumbersInTable: true
        tabWidth: 4
